### ISSUE TITLE
wbits parameter ignored for compression level 1 on 2.0.x branch

### ISSUE THREAD

**Issue by rhpvorderman** [zlib-ng/zlib-ng#1417]
Hi, I maintain python bindings for zlib-ng (https://github.com/pycompression/python-zlib-ng). I run a lot of compatibility tests with Python's zlib module to ensure smooth interoperability.

It turns out that using zng_deflate with compression level 1 overrides  the wbits setting in deflateInit in some way. This results in files that are always compressed with wbits 13 it seems. When I use wbits=-9 , I should also be able to inflate again with wbits=-9, however this is not possible and will throw an invalid window size error. 

This problem does not occur on the develop branch.

**Comment by nmoinvaz** [comment]
That sounds like it was fixed in this commit: https://github.com/zlib-ng/zlib-ng/commit/ce6789c7e093e8e6bb6fc591bbdf0f805999bdb9. But it is already included in latest zlib-ng release.

**Comment by rhpvorderman** [comment]
The problem still occurs on the zlib 2.0.6 branch and the coming zlib-ng 2.0.x branch.

**Comment by Dead2** [comment]
Maybe we should add a test for this, and have it run it once per algorithm.

I have tried to track down where this problem occurs, but my hunches have been wrong so far. @nmoinvaz any ideas?

**Comment by nmoinvaz** [comment]
I think we need more information in order to be able to track it back to a commit. @rhpvorderman can you provide instructions on how to run the tests, in your tests folder? Which test would trigger the error? It seems requirements-docs.txt might be missing pytest. Each time I install `python-zlib-ng` does it rebuild zlib-ng?

**Comment by rhpvorderman** [comment]
> @rhpvorderman can you provide instructions on how to run the tests, in your tests folder? 
```bash
git clone --recursive https://github.com/pycompression/python-zlib-ng.git
cd python-zlib-ng
virtualenv .venv  # python3-virtualenv needs to be installed or do pip install virtualenv first
source .venv/bin/activate
pip install . pytest
pytest tests/test_compat.py::test_compress
```
Last statement will yield 108 xfailed (expected failure) those are the tests that are failing.

> Each time I install python-zlib-ng does it rebuild zlib-ng?

Yes

It is maybe easier to recreate the test in this repo:
- Take a reasonably large chunk of data (128Kb should suffice) 
- compress it with all possible wbits, memlevel and compresslevel options
- For each option, check if it can be decompressed with the same wbits option.
Currently for level 1 any thing with a window size below 13 (regardless of header/trailer) fails. All other levels are OK.

**Comment by rhpvorderman** [comment]
Yes! Got it!

https://github.com/zlib-ng/zlib-ng/blob/2.0.x/deflate.c#L302-L305

```
#if !defined(NO_QUICK_STRATEGY) && !defined(S390_DFLTCC_DEFLATE)
    if (level == 1)
        windowBits = 13;
#endif
```

This happens in deflateInit2. This should be extremely easy to fix.
I will make a patch immediately.

**Comment by rhpvorderman** [comment]
Done https://github.com/zlib-ng/zlib-ng/pull/1431

**Comment by rhpvorderman** [comment]
FYI in the zlib-ng integration thread for cpython (https://github.com/python/cpython/issues/91349) they reckoned this commit fixed the problem https://github.com/zlib-ng/zlib-ng/commit/ce6789c7e093e8e6bb6fc591bbdf0f805999bdb9 . 

That commit removes  the WindowBits cap entirely and does some rebalancing. As a result the bug is also gone.
So you could also integrate that commit into 2.0.x. EDIT: Whoops, looks like that is already integrated as mentioned https://github.com/zlib-ng/zlib-ng/issues/1417#issuecomment-1416282624. 
Apparently the wbits cap has not been removed. Maybe for "no unexpected changes in patches" reasons? Anyway, my posted patch should fix the issue.

**Comment by nmoinvaz** [comment]
It looks like that was the right commit. However, I was wrong, I assumed it was merged into 2.0.x and stable branches based on the date of the commit and date of the release - it never got into any 2.0.x release.

**Comment by rhpvorderman** [comment]
Fixed
