### ISSUE TITLE
SIGBUS crash with git fetch on armv6 iOS

### ISSUE THREAD

**Issue by Un1q32** [zlib-ng/zlib-ng#1842]
The programs are compiled for armv6 iOS 3.0, but the crash happens when running on armv7s iOS 7.1.2, some other devices I've tested (armv6 iOS 3.0, armv6 iOS 3.1.3, armv7 iOS 4.1) don't crash for some reason, It happens with 2.2.3, 2.2.2, 2.1.7, and 2.1.8 and doesn't happen with vanilla zlib 1.3.1. Git version is 2.47.1

Backtrace:
![image](https://github.com/user-attachments/assets/74769018-825b-449d-b369-bedc556f6039)

**Comment by KungFuJesus** [comment]
Looks like yet another alignment requirement issue similar to what we saw on Android with aarch64 and the ld4 instruction

**Comment by Un1q32** [comment]
I've tested a bunch of devices
Crashes: iPhone 5 (armv7s) iOS 7.1.2, iPhone 5 (armv7s) iOS 8.4.1, iPhone 4S (armv7) iOS 6.1.3, iPod Touch 4 (armv7) iOS 6.1.6
Doesn't Crash: iPhone 3GS (armv7) iOS 4.1, iPod Touch 2 (armv6) iOS 3.1.3, iPod Touch 1 (armv6) iOS 3.0

**Comment by Un1q32** [comment]
I opted to just compile with `--without-neon`  as a workaround, that fixed it.

**Comment by Dead2** [comment]
@KungFuJesus @ccawley2011 Any ideas on how we can avoid/fix this?

---

@Un1q32 If you can, could you test compiling with CFLAGS="-DOPTIMAL_CMP=8" to see whether that fixes it?
ex:
`cmake . -DCMAKE_C_FLAGS="-DOPTIMAL_CMP=8"`

I am curious as to whether it gets set to 32 but should have been set to 8 to respect stricter alignment requirements. If this fixes it for you, then maybe we cannot just rely on `__ARM_FEATURE_UNALIGNED` being set.

But as far as I can tell, when going back and reviewing those changes with this bug in mind, the new code should be safe, maybe even safer than before since the old code seems to have always set it to 32 (defined UNALIGNED_OK) for all compilers not setting the gcc identifier.

There have been a lot of changes to chunkset and memread functions etc, so there are multiple PRs where this could have gone wrong.
If you could bisect the bug, that would be even better, but I know that can take a while so I understand if that is too much.

**Comment by Dead2** [comment]
And I just realized you already said that it also fails on 2.1.7. I guess you didn't find any version where it does work then.

Well, that neatly throws my theories away, since it is not caused by any recent change.
It might just be that we have always had a bug in adler32_neon, or it could also be a bug in the clang version you are using. We already have to disable VX on certain clang version in #1852.

Not sure how we can reproduce this locally or in CI either.

**Comment by ccawley2011** [comment]
I'll take a look at this later, but I agree with @KungFuJesus that it's an issue with stricter alignment requirements for the x4 NEON intrinsics compared to other loads and stores.

In the meantime, does it help to increase the alignment of the taps array from 16 to 32? The line number in the stack trace seems to point to an issue with reading from it.

**Comment by Un1q32** [comment]
> or it could also be a bug in the clang version you are using.

I'm using the latest clang 19.1.7.

> could you test compiling with CFLAGS="-DOPTIMAL_CMP=8"

passing `CFLAGS="-DOPTIMAL_CMP=8" ./configure` did not fix the issue.

> In the meantime, does it help to increase the alignment of the taps array from 16 to 32?

Changing `ALIGNED_(16)` to `ALIGNED_(32)` on line 14 of arch/arm/adler32_neon.c did not fix the issue.

**Comment by KungFuJesus** [comment]
I believe it needs to be 64.

**Comment by KungFuJesus** [comment]
@dead2 the fix would be the same we did for android, where we use the emulated ld4 implementation

**Comment by Un1q32** [comment]
> I believe it needs to be 64.

Still doesn't fix it.

**Comment by ccawley2011** [comment]
> > I believe it needs to be 64.
> 
> Still doesn't fix it.

Just to clarify, is it failing on the same line as before, or is it a different one?

**Comment by Un1q32** [comment]
I never checked, I just got the same error, I'll check again but this time with a debugger.

**Comment by Un1q32** [comment]
![Image](https://github.com/user-attachments/assets/ab1921d7-b7d0-4ef7-b968-c9736fc9c4d2)

**Comment by KungFuJesus** [comment]
It's not just the taps variable, you'd need to enforce alignment of the buffer itself. At the moment we ensure 16 byte alignment when doing so doesn't completely bypass the neon routines. You'd need to alter it to do single byte sums until you hit 64 byte alignment.

**Comment by ccawley2011** [comment]
This is only tangentially related, but I get the impression that the code that handles aligning the buffer isn't working correctly even for 16 byte alignment - I'm currently testing a branch that explicitly makes use of NEON alignment hints, but I'm getting a bus error when running the unit tests, and adding `assert(((uintptr_t)buf & 15) == 0);` to the top of `NEON_accum32` results in the assert failing.

**Comment by KungFuJesus** [comment]
The intent of the code was not to always ensure alignment but to ensure alignment when doing so doesn't bypass neon entirely. There's a check to make sure that doesn't happen. Of course, given the alignment requirements of the load 4 registers at once obstruction, maybe we should just do a single 128 bit load anyhow.

**Comment by neheb** [comment]
@Un1q32 define

```
__ANDROID__
```

and the crash will go away.

related issues:

https://github.com/zlib-ng/zlib-ng/pull/1824
https://github.com/zlib-ng/zlib-ng/issues/1844

**Comment by Un1q32** [comment]
> [@Un1q32](https://github.com/Un1q32) define
> 
> ```
> __ANDROID__
> ```
> 
> and the crash will go away.
> 
> related issues:
> 
> [#1824](https://github.com/zlib-ng/zlib-ng/pull/1824) [#1844](https://github.com/zlib-ng/zlib-ng/issues/1844)

That fixes it, I've made a PR to do this fix automatically.

**Comment by KungFuJesus** [comment]
I believe this has been fixed, no?

**Comment by Un1q32** [comment]
Yeah

**Comment by Un1q32** [comment]
Though when using clang >=19 with the latest release it still happens, the fix is in master though.
