### ISSUE TITLE
Cross-Compiling with mingw gives libzlib.lib, even though ZLIB_COMPAT is ON (expected libz.lib)

### ISSUE THREAD

**Issue by Xaymar** [zlib-ng/zlib-ng#971]
I'm trying to cross-compile zlib-ng for Windows using the provided toolchain while keeping zlib compatibility and found that the generated library files are all suffixed with `lib`. This breaks the expected compatibility with zlib, as the name should be `libz`, not `libzlib`. Below is my build command:

```
cmake -H. -Bbuild/build \
	-DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-mingw-x86_64.cmake \
	-DCMAKE_BUILD_TYPE=RELEASE -DZLIB_COMPAT=ON -DZLIB_ENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=ON \
	-DCMAKE_INSTALL_PREFIX=./build/distrib/
cmake --build build/build --target install
# <snip> .lib stuff for msvc requirements
# Why do i need to do this with ZLIB_COMPAT=ON?
cp ./build/distrib/lib/libzlib.dll.a ./build/distrib/lib/libz.dll.a
```
Note that the generated zlib.pc file also has the link command `-lz`, not `-lzlib`. This appears to be the culprit: https://github.com/zlib-ng/zlib-ng/blob/develop/CMakeLists.txt#L996-L1001

**Comment by nmoinvaz** [comment]
This should be resolved now in 2.0.4.

**Comment by inkydragon** [comment]
This problem still exists.

https://github.com/zlib-ng/zlib-ng/blob/92107a92d3cfb11cc464c24ef2a73c2d7d05d2ba/CMakeLists.txt#L956-L975

Windows + cygwin + build flag:
+ NOT DEFINED BUILD_SHARED_LIBS: #L958, `libzlib`
+ `-DBUILD_SHARED_LIBS=ON`: #L958, `libzlib`
+ `-DBUILD_SHARED_LIBS=OFF`: #L968 -> #L972, `libz`
+ We will never execute line #L962~#L967

When do we need `zlib` as OUTPUT_NAME?

Or maybe you forgot to remove the prefix `lib`.
The library prefix is defined by the following two variables, both with the default value of `lib`.
+ `CMAKE_SHARED_LIBRARY_PREFIX`
+ `CMAKE_STATIC_LIBRARY_PREFIX`

xref: JuliaPackaging/Yggdrasil#3614

----

My proposal: replace #L957~#L974 with:
```cmake
    if(NOT DEFINED BUILD_SHARED_LIBS OR BUILD_SHARED_LIBS)
        # Shared library
        set_target_properties(zlib PROPERTIES OUTPUT_NAME z${SUFFIX})
    elseif(NOT BUILD_SHARED_LIBS)  
        # Static library
        if(MSVC)
            set_target_properties(zlibstatic PROPERTIES OUTPUT_NAME zlibstatic${SUFFIX})
        else()
            set_target_properties(zlibstatic PROPERTIES OUTPUT_NAME z${SUFFIX})
        endif()
    endif()
```

|        | BUILD_SHARED_LIBS=ON<br>OR NOT DEFINED | BUILD_SHARED_LIBS=OFF |
|--------|:--------------------------------------:|:---------------------:|
| MSVC   | libz                                   | libzstatic            |
| Others | libz                                   | libz                  |

**Comment by mtl1979** [comment]
Targets can't have duplicate names... Windows doesn't use .a extension for static libraries.

**Comment by inkydragon** [comment]
cmake + cygwin may be buggy, cmake never sets the `CYGWIN` flag in my local build tests.

So I use different flags to get the following compilation product:

+ `-DBUILD_SHARED_LIBS=ON`: libzlib.dll.a + libzlib1.dll
+ `-DBUILD_SHARED_LIBS=OFF`: libz.a
+ not set: libzlib.dll.a + libz.a + libzlib1.dll

> Windows doesn't use .a extension for static libraries.

Yes, Windows use `.lib` for static libraries, cygwin may use `.dll.a`.

**Comment by mtl1979** [comment]
It has to be fixed in cmake first... When zlib was released, cmake did support neither Cygwin or MinGW... This can be verified from cmake's own documentation when those defines were added to cmake's configuration step.

**Comment by inkydragon** [comment]
The CYGWIN flag issue can be bypassed, so skip it first.

The master branch is still using the name `libzlib` when generating shared libraries.
I would like to say that this issue has not been resolved yet.

So my question is when do we need this name?
If none are needed, then I have the following proposal.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dcd07ad..9268e50 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -956,7 +956,7 @@ endforeach()
 if(WIN32)
     # Shared library
     if(NOT DEFINED BUILD_SHARED_LIBS OR BUILD_SHARED_LIBS)
-        set_target_properties(zlib PROPERTIES OUTPUT_NAME zlib${SUFFIX})
+        set_target_properties(zlib PROPERTIES OUTPUT_NAME z${SUFFIX})
     endif()
     # Static library
     if(NOT DEFINED BUILD_SHARED_LIBS)
```

+ `-DCYGWIN=1 -DBUILD_SHARED_LIBS=ON`: libz.dll.a + libz.dll
+ `-DCYGWIN=1 -DBUILD_SHARED_LIBS=OFF`: libz.a
+ `-DCYGWIN=1`: libz.dll.a + libz.a + libz.dll

**Comment by mtl1979** [comment]
We can't ignore `CYGWIN` flag as it would break build when using Visual C++.

**Comment by inkydragon** [comment]
> We can't ignore CYGWIN flag

Apologize for my poor English.

I mean, ignoring the CYGWIN flag issue.
Not to remove the related if branch.

Let's focus on the shared library name issue.

**Comment by mtl1979** [comment]
Those two things are mutually inclusive... Supporting Cygwin, MinGW or even Visual C++ would require increasing the minimum required version for cmake way too high... That's why we still have nmake Makefiles for Visual C++.

**Comment by inkydragon** [comment]
Actually the master branch already supports compilation on Cygwin, 
but there is something wrong with the name of the compiled product.
It's the same as the title of this issue

**Comment by mtl1979** [comment]
I'm just saying using cmake on Cygwin with `ZLIB_COMPAT` set is unsupported combination due to limits of cmake.
